name: Test and Publish

on:
  push:

env:
  IMAGE_NAME: ${{ vars.DOCKER_ORG }}/idp-id-broker

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    timeout-minutes: ${{ fromJSON(vars.DEFAULT_JOB_TIMEOUT_MINUTES) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check PSR2
        run: docker compose -f actions-services.yml run --rm app ./check-psr12.sh
      - name: Run unit tests
        run: docker compose -f actions-services.yml run --rm app ./run-tests.sh

  build-and-publish:
    name: Build and Publish
    needs: tests
    runs-on: ubuntu-latest
    timeout-minutes: ${{ fromJSON(vars.DEFAULT_JOB_TIMEOUT_MINUTES) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            GITHUB_REF_NAME=${{ github.ref_name }}
